language: node_js
node_js:
    - '0.11'
    - '0.10'
    - '0.8'
matrix:
    fast_finish: true
    allow_failures:
        - node_js: '0.11'
before_install:
    - npm update -g npm
script:
    - ant -f build.xml ci
